# Generated by Django 5.2.2 on 2025-06-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='voice_over',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_over', models.CharField(max_length=255)),
                ('foto_vc', models.ImageField(upload_to='voice_over')),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('judul_in_english', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('tanggal_rilis', models.DateTimeField()),
                ('poster', models.ImageField(upload_to='poster/')),
                ('season', models.IntegerField(choices=[(1, 'Season 1'), (2, 'Season 2'), (3, 'Season 3'), (4, 'Season 4')])),
                ('genre', models.ManyToManyField(to='anime.genre')),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinopsis', models.TextField()),
                ('judul_in_english', models.CharField(max_length=255)),
                ('episode', models.IntegerField(choices=[(1, 'Episode 1'), (2, 'Episode 2'), (3, 'Episode 3'), (4, 'Episode 4'), (5, 'Episode 5'), (6, 'Episode 6'), (7, 'Episode 7'), (8, 'Episode 8'), (9, 'Episode 9'), (10, 'Episode 10'), (11, 'Episode 11'), (12, 'Episode 12'), (13, 'Episode 13')])),
                ('video', models.FileField(upload_to='anime')),
                ('judul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_episodes', to='anime.anime')),
                ('voice_over', models.ManyToManyField(to='anime.voice_over')),
            ],
        ),
    ]
