# Generated by Django 5.2.2 on 2025-06-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='video',
        ),
        migrations.CreateModel(
            name='Animenya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField(choices=[(1, 'Episode 1'), (2, 'Episode 2'), (3, 'Episode 3'), (4, 'Episode 4'), (5, 'Episode 5'), (6, 'Episode 6'), (7, 'Episode 7'), (8, 'Episode 8'), (9, 'Episode 9'), (10, 'Episode 10'), (11, 'Episode 11'), (12, 'Episode 12'), (13, 'Episode 13')])),
                ('video', models.FileField(upload_to='anime')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.anime')),
            ],
            options={
                'verbose_name_plural': 'Animenya',
                'ordering': ['episode'],
            },
        ),
    ]
