# Generated by Django 5.2.2 on 2025-06-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_details_video_animenya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='judul',
            new_name='Judul',
        ),
    ]
