# Generated by Django 5.2.2 on 2025-06-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_rename_judul_details_judul'),
    ]

    operations = [
        migrations.AddField(
            model_name='animenya',
            name='urls',
            field=models.URLField(null=True),
        ),
    ]
