# Generated by Django 5.2.2 on 2025-06-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_studio_details_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='judul',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(),
        ),
    ]
