# Generated by Django 5.2.2 on 2025-06-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_anime_judul_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='tanggal_rilis',
            field=models.DateField(),
        ),
    ]
