# Generated by Django 5.2.2 on 2025-06-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_alter_anime_tanggal_rilis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='characters/')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='anime.details')),
            ],
        ),
    ]
