# Generated by Django 5.2.2 on 2025-06-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_character_anime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['nama'], 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
    ]
