# Generated by Django 5.2.2 on 2025-06-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_alter_character_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='episode',
        ),
    ]
